version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
      args:
        NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/usr/src/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - "SERVER_PORT:${SERVER_PORT}"
    depends_on:
      - mongo

  mongo:
    build:
      context: ./
      dockerfile: Dockerfile.mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "mongodb_data:/data/db"
    environment:
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    logging:
      driver: none

volumes:
  mongodb_data:
    driver: local